version: "3"
services:
  web_app:
    build: ./web_app
    ports:
      - "5000:5000"
    environment:
      - URI=${MONGO_URI}
      - DATABASE=accounts
      - COLLECTION=users

volumes:
  mongodb-data:
