version: "3"
services:
  web_app:
    build:
      context: ./web_app
      dockerfile: ./web_app/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - SPOON_SECRET=8c6bd3a0f40744e3967ff515544ef999
      - URI=mongodb://mongo:27017/
      - DATABASE=accounts
      - COLLECTION=users

  mongo:
    build: ./mongodb
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - DATABASE=accounts
      - COLLECTION=users

volumes:
  mongodb-data:
