version: "3"
services:
  web_app:
    build: ./web_app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - URI=mongodb://mongo:27017/
      - DATABASE=accounts
      - COLLECTION=users

  mongo:
    build: ./mongodb
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - DATABASE=accounts
      - COLLECTION=users

volumes:
  mongodb-data:
