version: "3.8"
services:
  web_app:
    build: .
    depends_on:
      - mongodb
    ports:
      - "5000:5000"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
