version: "3"
services:
  mongodb:
    build: ./mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  web_app:
    build: ./web_app
    depends_on:
      - mongodb
    ports:
      - "5000:5000"

volumes:
  mongodb-data:
