version: "3"
services:
  web_app:
    build: ./web_app
    ports:
      - "5000:5000"
    environment:
      - URI=mongodb+srv://js11692:emergencyBlimp@cluster0.agkibmg.mongodb.net/?retryWrites=true&w=majority
      - DATABASE=accounts
      - COLLECTION=users

volumes:
  mongodb-data:
