version: "3"
services:
  # mongodb:
  #   build: ./mongodb
  #   container_name: mongodb
  #   ports:
  #     - "27012:27012"
  #   environment:
  #     - DATABASE=Accounts
  #     - COLLECTION=accounts
  #   volumes:
  #     - mongodb-data:/data/db
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"

  web_app:
    build: ./web_app
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    environment:
      - URI=mongodb+srv://js11692:emergencyBlimp@cluster0.agkibmg.mongodb.net/?retryWrites=true&w=majority
      - DATABASE=Accounts
      - COLLECTION=accounts

volumes:
  mongodb-data:
