name: check lint and format
on: [push, pull_request]

jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          sudo apt-get update

      - name: Install dependencies
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          # python -m pip install pipenv pylint
          pipenv lock
          pipenv sync --dev --python $(which python)
          pipenv shell --fancy --python $(which python)
          pipenv install python-dotenv
      
      - name: Lint with pylint
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          pipenv run pylint **/*.py

      # - name: Lint with pylint
      #   if: ${{ hashFiles('**/*.py') != '' }}
      #   run: |
      #     pylint $(find . -name '*.py')  # Use find command for Python files

      - name: Format with black
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          pipenv run black --diff --check .