name: check lint and format
on: [push, pull_request]

jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update

      - name: Install dependencies
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --dev --python $(which python)
      
      - name: List installed packages
        run: |
          pipenv run pip list
      
      # - name: Lint with pylint
      #   if: ${{ hashFiles('**/*.py') != '' }}
      #   run: |
      #     pipenv run pylint **/*.py

      - name: Lint with pylint
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          pipenv shell
          pylint $(find . -name '*.py')

      - name: Format with black
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          pipenv run black --diff --check .