name: pytest tests and coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: 'Create fake env file'
        run: |
          touch .env
          echo SPOON_SECRET=123abc >> .env
          echo URI=:2 >> .env
          echo DATABASE=a >> .env
          cat .env
      - name: Generate Report
        run: |
          find . -name "*.pyc" -exec rm -f {} \;
          pip install pytest-cov
          pytest --cov-config=.coveragerc --cov=./web_app/tests --cov-report=xml
          python -m coverage run -m pytest
          python -m coverage report --omit=*/tests/*